export enum LocalStorageKeys {
  THEME_MODE = 'THEME_MODE',
  BACKGROUND_OPTION_INDEX = 'BACKGROUND_OPTION_INDEX',
  BACKGROUND_OPTIONS = 'BACKGROUND_OPTIONS',
  CUSTOM_BACKGROUNDS = 'CUSTOM_BACKGROUNDS',
  SELECTED_BACKGROUND_IMAGE_ID = 'SELECTED_BACKGROUND_IMAGE_ID',
}
